[package]
name = "backend"
publish = false
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["fullstack"] }
axum = { workspace = true, optional = true }
tracing = "0.1.41"

[features]
server = [
    "axum",
]
